server.port=8080

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

server.tomcat.threads.max=10

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.datasource.hikari.schema=batch
spring.datasource.hikari.maximum-pool-size=10

#spring.data.mongodb.database=test
#spring.data.mongodb.port=27017
spring.mongodb.embedded.version=4.4.9
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

spring.flyway.enabled=false

decorator.datasource.flexy-pool.threshold.connection.acquire=-1
decorator.datasource.flexy-pool.threshold.connection.lease=0

logging.level.root=INFO
logging.level.com.example.demo=TRACE
#logging.file.name=demo/application-logs/logs.log
logging.logback.rollingpolicy.max-file-size=2MB
logging.logback.rollingpolicy.max-history=100
logging.logback.rollingpolicy.total-size-cap=200MB
logging.logback.rollingpolicy.file-name-pattern=demo/application-logs/logs-%d{yyyy-MM-dd}.%i.log

#server.tomcat.basedir=demo/access-logs
#server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%t %a "%r" %s (%D ms)

properties.map={name:'John',age:'25'}
properties.list=John,Max
properties.text=John

product.listener.enabled=false
product.cron=0 * * ? * *
product.externalService.url=http://product-external-service

outbox.cron=0/1 * * ? * *

kafka.publisher.cron=0/10 * * ? * *

internal.publisher.cron=0/10 * * ? * *

external.service.url=http://external-service

#spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.consumer.bootstrap-servers=localhost:9092

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.batch.job.enabled=false
spring.batch.isolation-level-for-create=default
spring.batch.jdbc.initialize-schema=always

game.engine.maxScheduledDrawsPerGame={8:50}

batch.basic.entry.job.chunkSize=5
batch.basic.entry.job.pageSize=10
batch.basic.entry.job.throttleLimit=8

batch.entry.job.chunkSize=20
batch.entry.job.pageSize=80
batch.entry.job.throttleLimit=8

batch.entry.job.processor.corePoolSize=4
batch.entry.job.processor.maxPoolSize=8
batch.entry.job.processor.queueCapacity=50

batch.entry.job.async.launcher.corePoolSize=0
batch.entry.job.async.launcher.maxPoolSize=4
batch.entry.job.async.launcher.queueCapacity=10
batch.entry.job..async.launcher.keepAliveSeconds=30
batch.entry.job..async.launcher.allowCoreThreadTimeout=true

batch.entry.cron=0/10 * * ? * *
#batch.entry.cron=0 0 0 ? * *

batch.entry.automatic.retry.cron=0 0/3 * ? * *
#batch.entry.automatic.retry.cron=0 0 0 ? * *
