CREATE TABLE VISIT (
    ID                 BIGSERIAL    PRIMARY KEY,
    VISIT_DATE         TIMESTAMP    NOT NULL,
    PAYMENT            VARCHAR(20)  NOT NULL,
    REMINDER_SENT      BOOLEAN      NOT NULL,
    PATIENT_ID         BIGINT       NOT NULL,
    FOREIGN KEY (PATIENT_ID)
    REFERENCES PATIENT (ID)
);