CREATE TABLE VISIT (
    ID                 BIGSERIAL    PRIMARY KEY,
    DATE               TIMESTAMP    NOT NULL,
    PAYMENT_STATUS     VARCHAR(20)  NOT NULL,
    STATUS             VARCHAR(10)  NOT NULL,
    REMINDER_SENT      BOOLEAN      NOT NULL,
    PATIENT_ID         BIGINT       NOT NULL,
    FOREIGN KEY (PATIENT_ID)
    REFERENCES PATIENT (ID)
);